spring:
  datasource:        
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.101:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 192.168.1.118
    port: 5672
    username: admin
    password: 123456  
  redis:
    host: 192.168.1.118
    port: 6379
# eureka:
#   client:
#     service-url: 
#       defaultZone: http://localhost:8761/eureka/
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  dev
